### ISSUE TITLE
when defining 1:m relationship (issue)

### ISSUE THREAD

**Issue by Rowadz** [MohammedAl-Rowad/pollux#17]
the ids are not unique so all the nested documents are the same for each document 

see the ids in this generated file

https://github.com/MohammedAl-Rowad/redux-toolkit-adapters-and-thunks/blob/main/pollux-api/db.json

the ids for tags and likes are the same for each comment, this should change to be unique

**Comment by reynaldysaputra** [comment]
Hi thanks for opening up this problem, I'm learning redux through you, but could you please create all the unique ids in pollux-API, so we can play around with this data without worrying about performance issues.

**Comment by Rowadz** [comment]
@Yousef-NJ I created a temp solution for this until we find a good way to do it 

I just returned the old function AND limited the nested relational data to only 10 documents for now, until we find a way to speed it up


```js
    const resWithRelations = res.map((obj) => ({
      ...obj,
      ...relations.reduce(
        (prev, { name, id }) => ({
          ...prev,
          [name]: generateFakeData(relationsProps[id], 10), // LOOK HERE
        }),
        {}
      ),
    }))
```

> I deployed the temp fix

**Comment by Rowadz** [comment]
Related to https://github.com/MohammedAl-Rowad/pollux/issues/30

**Comment by Rowadz** [comment]
The ids are now unique after adding web workers, but generating a lot of data is slow 

for example 100 users with 100 comments will generate `10_000` documents which is fine and kinda fast now

> after merging https://github.com/MohammedAl-Rowad/pollux/pull/31
