### ISSUE TITLE
Little typo in toast notification

### ISSUE THREAD

**Issue by mpagels** [MohammedAl-Rowad/pollux#21]
After clicking the yellow Button to create a `SQL` insert, two typos are displayed in the toast notification.

- [ ] cehck
- [ ] conosle

![grafik](https://user-images.githubusercontent.com/54703643/151939986-bd39d3f0-baba-4247-8f82-2b6d29b2500f.png)

**Comment by MohammedAl-Rowad** [comment]
oops, this button should not be deployed 

I was working on this but didn't finish it, that's a mistake 


I'll remove it soon

**Comment by Rowadz** [comment]
oops, I'll fix it 

thank you for reporting this

**Comment by Rowadz** [comment]
fixed
