### ISSUE TITLE
Navigating directly to pollux/generate does not work

### ISSUE THREAD

**Issue by rossneilson** [MohammedAl-Rowad/pollux#6]
When you navigate directly to or refresh the page on https://mohammedal-rowad.github.io/pollux/generate it throws a 404 error. Likely a routing issue.

**Comment by Rowadz** [comment]
This is now fixed, 
I found the solution here
https://stackoverflow.com/questions/46056414/getting-404-for-links-with-create-react-app-deployed-to-github-pages

the link now will be :

https://mohammedal-rowad.github.io/pollux/#/generate

notice the `#` in the URL
